- .circleci/config.yml
- CMakeLists.txt
- etc/cppcheck-suppressions.txt
- toolbox/contrib/libutil.h
Add support for CircleCI continuous integration and delivery, so that pull requests can be built and tested in a pristine environment before they are merged.
> Add CircleCI build

- toolbox/util/Slot.hpp
- toolbox/util/Slot.ut.cpp
- toolbox/util/Traits.hpp
- toolbox/util/Traits.ut.cpp
Add support for rvalue Argument type for BasicSlot
Add FunctionTraits Specialisation for noexcept member function
> Support rvalue Arg type in Slot

- .circleci/config.yml
- image/CMakeLists.txt
Automatically publish Doxygen documentation to GitHub pages when master branch is built by CircleCI.
> Publish Doxygen documentation

- Doxyfile.in
- README.md
- toolbox/io/Epoll.hpp
- toolbox/io/EpollReactor.cpp
- toolbox/ipc/Futex.hpp
- toolbox/ipc/Shm.hpp
- toolbox/net/Resolver.hpp
- toolbox/util/Exception.cpp
Minor improvements to cleanup generated Doxygen documentation.
> Minor Doxygen improvements

- .circleci/config.yml
- CMakeLists.txt
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- Doxyfile.in
- LICENSE.md
- README.md
- doc/Algorithms.md
- doc/BuildFromSource.md
- doc/Concurrency.md
- doc/DataStructures.md
- doc/Dependencies.md
- doc/Messaging.md
- doc/MoSCoW.md
- doc/StringHandling.md
- toolbox/Config.h.in
Cleanup README and contribute documents that were originally part of the Swirly Cloud project.
> Add Markdown documents

- .circleci/config.yml
Create GitHub release and upload artefacts for version tags and master builds.
DEV-446
> Automate GitHub release

- CMakeLists.txt
- README.md
Change the documentation subdomain from doc to docs.
> Change subdomain to docs

- toolbox/io.hpp
- toolbox/ipc.hpp
- toolbox/net.hpp
- toolbox/sys.hpp
- toolbox/util.hpp
Result of running:
```
for dir in *; do [[ -d $dir ]] && ls $dir/*.hpp | { head -n 16 io/Buffer.hpp; echo -e "\n#ifndef TOOLBOX_${dir^^}_HPP\n#define TOOLBOX_${dir^^}_HPP\n"; sed 's/.*\/\(.*\)/#include "\1"/'; echo -e "\n#endif // TOOLBOX_${dir^^}_HPP"; } > $dir/$dir.new && mv $dir/$dir.new $dir/$dir.hpp ; done
```
> GH-14 Added convenience headers

- CONTRIBUTING.md
Add quotes from Go proverbs along with some general advice on application logging.
> Update contributor's guide

- toolbox/util/IntTypes.hpp
Add Int16Policy specialisation and derived Id16 type and suffix operator.
> Add int16 IntPolicy specialisation

- CMakeLists.txt
- toolbox/CMakeLists.txt
Enable coverage builds and report generation.
> GH-22: Add support for coverage build

- toolbox/ipc/MpmcQueue.hpp
The `mmap()` function retains a reference to the file associated with the file descriptor, so the file can be safely closed once the mapping has been established.
> Close memory mapped file

- toolbox/CMakeLists.txt
- toolbox/util/String.hpp
- toolbox/util/String.ut.cpp
- toolbox/util/Tuple.cpp
- toolbox/util/Tuple.hpp
- toolbox/util/Tuple.ut.cpp
Add a generic make_string function with variadic args.
> Add make_string function

- .circleci/config.yml
- toolbox/ipc/MpmcQueue.hpp
- toolbox/util/Traits.ut.cpp
Add clang-format check to the circleci steps
Closes #59
> Require clang-formatted code

- example/EchoClnt.cpp
- example/EchoServ.cpp
- toolbox/http/Conn.hpp
- toolbox/http/Serv.hpp
- toolbox/net/StreamAcceptor.hpp
- toolbox/net/StreamConnector.hpp
The want_write flag should be set so that in matches the corresponding bit in the socket's I/O event mask. Also rename on_sock_init to on_sock_prepare.
> Want write flag not set

- example/EchoClnt.cpp
- toolbox/CMakeLists.txt
- toolbox/http/Conn.hpp
- toolbox/io/Disposable.cpp
- toolbox/io/Disposable.hpp
- toolbox/io/Disposable.ut.cpp
- toolbox/util.hpp
- toolbox/util/Tuple.hpp
The BasicDisposable class template exposes a public dispose method that may be safely called from callback functions while a lock is held.
> BasicDisposable class template

- bench/CMakeLists.txt
- bench/Timer.bm.cpp
- toolbox/http/Conn.hpp
- toolbox/io/Buffer.cpp
- toolbox/io/Buffer.hpp
- toolbox/io/Muxer.hpp
- toolbox/io/Reactor.cpp
- toolbox/net/StreamConnector.hpp
Reactor and HTTP server improvements designed to reduce context switches.
> Performance improvements

- toolbox/io/Runner.cpp
Spin the Reactor thread for a few cycles after work was done to avoid putting the thread to sleep and incurring scheduling latency costs.
> Keep Reactor thread warm

- toolbox/http/Conn.hpp
Rework read loop, so that input is flushed (parsed) on each of the three exit conditions.
> Input not flushed on loop exit

- example/EchoClnt.cpp
- example/EchoServ.cpp
- toolbox/CMakeLists.txt
- toolbox/http/Conn.hpp
- toolbox/http/Serv.hpp
- toolbox/http/Stream.hpp
- toolbox/io/Buffer.cpp
- toolbox/io/Buffer.hpp
- toolbox/io/Runner.cpp
- toolbox/io/Timer.hpp
- toolbox/net/Endian.cpp
- toolbox/net/Endian.hpp
- toolbox/net/Frame.cpp
- toolbox/net/Frame.hpp
- toolbox/net/Frame.ut.cpp
- toolbox/net/Runner.cpp
- toolbox/sys/Log.hpp
Add a parser for length-prefixed frames as a first step towards a general purpose streaming server for binary messaging.
> Parser for length-prefixed frames

- toolbox/sys/Time.hpp
Add time_t conversions to MonoClock.
> Add time_t conversions

- .circleci/config.yml
- toolbox/CMakeLists.txt
- toolbox/net.hpp
- toolbox/net/RateLimit.cpp
- toolbox/net/RateLimit.hpp
- toolbox/net/RateLimit.ut.cpp
- toolbox/sys/Time.hpp
Add rate limiter for controlling the rate of requests sent or received over the network.
> Add rate limiter

- CMakeLists.txt
- etc/CMakeLists.txt
- etc/cmake/CMakeLists.txt
- etc/cmake/FindSystemTap.cmake
- toolbox/CMakeLists.txt
- toolbox/Config.h.in
- toolbox/net/RateLimit.cpp
- toolbox/net/RateLimit.hpp
- toolbox/net/RateLimit.ut.cpp
- toolbox/sys/Trace.cpp
- toolbox/sys/Trace.hpp
Add support for Dtrace probe macros
> feat: add Dtrace macros

- .github/workflows/ci-build.yml
Rename build.yml file to ci-build.yml.
> Rename workflow file

- .github/workflows/ci-build.yml
Rename test job to build for consistency.
> Rename workflow job

- .github/workflows/ci-build.yml
Add a condition to skip the CI build when the commit message contains "[skip ci]".
DEV-1882
> DEV-1882: add skip ci condition to actions

- .github/workflows/ci-build.yml
- .github/workflows/gh-pages.yml
- .github/workflows/release.yml
- toolbox/util/Options.ut.cpp
> chore: upgrade toolchain to support C++20

- toolbox/io/Timer.hpp
- toolbox/util/IntTypes.hpp
- toolbox/util/StringBuf.hpp
- toolbox/util/Version.hpp
Minor changes to make constexpr and noexcept contracts more explicit.
> feat: noexcept spaceship operators

- toolbox/contrib/http_parser.c
- toolbox/contrib/http_parser.h
- toolbox/contrib/robin_hood.h
- toolbox/contrib/ryu/d2fixed.c
- toolbox/contrib/ryu/d2s_intrinsics.h
Apply latest patches to the HTTP parser, Robin Hood hasher, and RYU.
DEV-2196
> chore: update external dependencies

- example/EchoClnt.cpp
- example/EchoServ.cpp
- example/HttpServ.cpp
- toolbox/io/Runner.cpp
- toolbox/io/Runner.hpp
Add busy cycles parameter to ReactorRunner class.
> feat: busy cycles parameter

- toolbox/sys/Thread.cpp
- toolbox/sys/Thread.hpp
- toolbox/sys/Thread.ut.cpp
Extend ThreadConfig to support scheduling policy configuration.
> feat: thread scheduling policy

- toolbox/util/RobinHood.hpp
Add type aliases for Robin Hood hash sets.
> feat: Robin Hood hash set type aliases

- .github/workflows/ci-build.yml
- .github/workflows/gh-pages.yml
- .github/workflows/release.yml
- cppcheck.sh.in
- toolbox/sys/Signal.cpp
- toolbox/sys/Signal.hpp
Restart sigwaitinfo if interrupted by unblocked signal.
Update to latest toolchain.
Fix broken cppcheck for robin_hood.h.
> feat: minor fixes and updates

- toolbox/io/Buffer.hpp
- toolbox/sys/Log.hpp
Add function operator to Log class for writing unformatted data to the log.
DEV-2696
> feat(log): unformatted log output

- .github/workflows/ci-build.yml
- .github/workflows/gh-pages.yml
- .github/workflows/release.yml
- toolbox/util/String.ut.cpp
> build: update to toolchain v0.5.0

- toolbox/CMakeLists.txt
- toolbox/sys/Limits.hpp
- toolbox/util.hpp
- toolbox/util/Trans.cpp
- toolbox/util/Trans.hpp
- toolbox/util/Trans.ut.cpp
Add an abstraction for implementing transactional behaviour.
DEV-3133
> feat: add transaction abstraction

- .github/workflows/ci-build.yml
- .github/workflows/gh-pages.yml
- .github/workflows/release.yml
> build: update to toolchain v0.8.0

- CMakeLists.txt
- toolbox/CMakeLists.txt
> feat: enable link-time optimisations

- .github/workflows/ci-build.yml
- .github/workflows/gh-pages.yml
- .github/workflows/release.yml
- CMakeLists.txt
> build: update toolset to v0.10.0

- .github/workflows/ci-build.yml
- .github/workflows/gh-pages.yml
- .github/workflows/release.yml
- CMakeLists.txt
> build: update toolset to v0.11.0

- toolbox/CMakeLists.txt
- toolbox/http/Conn.hpp
- toolbox/http/Stream.cpp
- toolbox/io/Stream.cpp
- toolbox/io/Stream.hpp
- toolbox/util/StringBuf.hpp
Add a Stream class to the io package that provides an IO stream wrapper around a Buffer.
DEV-2663
> feat: add stream to io package

- CMakeLists.txt
- etc/cppcheck-suppressions.txt
- toolbox/CMakeLists.txt
- toolbox/http/Conn.hpp
- toolbox/http/Parser.hpp
- toolbox/http/Parser.ut.cpp
- toolbox/resp.hpp
- toolbox/resp/Exception.cpp
- toolbox/resp/Exception.hpp
- toolbox/resp/Parser.cpp
- toolbox/resp/Parser.hpp
- toolbox/resp/Parser.ut.cpp
Add a basic parser for version 2 of the Redis serialisation protocol along with a comprehensive test suite.
DEV-3364
> feat: add basic Redis parser

- toolbox/resp/Parser.ut.cpp
Minor improvements and refactoring to the RESP parser unit-tests.
DEV-3364
> refactor(resp): minor unit-test refactoring

- bench/Log.bm.cpp
- toolbox/sys/Logger.hpp
Will change some of the logger benchmark names to better show the
differences between each, also reorders them slightly and adds a new
benchmark.
DEV-1325
> test: refactor logger benchmarks

- bench/Util.bm.cpp
- toolbox/util/String.ut.cpp
- toolbox/util/Utility.ut.cpp
A micro-benchmark for string to boolean conversions.
> chore(test): add stob micro-benchmark

- toolbox/io/Reactor.cpp
Add USDT probes for measuring the time taken to process reactor events.
> feat: add USDT probes for reactor cycle

- .github/workflows/ci-build.yml
- .github/workflows/gh-pages.yml
- .github/workflows/release.yml
> build: update toolset to v0.12.0

- .github/workflows/ci-build.yml
- .github/workflows/gh-pages.yml
- .github/workflows/release.yml
> chore: update toolset to v0.14.0

- toolbox/net/RateLimit.cpp
- toolbox/net/RateLimit.hpp
- toolbox/net/RateLimit.ut.cpp
- toolbox/sys/Time.hpp
Reduce rate window bucket size from second to deci-second.
SDB-2822
> SDB-2822: Reduce rate window bucket size

- toolbox/sys/Trace.hpp
> fix(probe): un-inline final callback of scoped probe

- toolbox/http/Types.hpp
> feat(http): add RequestTimeout constant

- .github/workflows/ci-build.yml
- .github/workflows/gh-pages.yml
- .github/workflows/release.yml
> chore: update toolset to v0.16.0

- toolbox/CMakeLists.txt
- toolbox/io.hpp
- toolbox/util.hpp
- toolbox/util/StreamInserter.cpp
- toolbox/util/StreamInserter.hpp
- toolbox/util/StreamInserter.ut.cpp
StreamInserter is a class template designed to simplify I/O manipulator and stream inserter implementations by reducing boiler-plate code.
SDB-2980
> feat(util): add stream inserter template

- toolbox/util/StreamInserter.hpp
- toolbox/util/StreamInserter.ut.cpp
Add template parameter for the stream type to the StreamInserter class template.
SDB-2980
> feat(util): stream inserter with stream type template param

- toolbox/net/Endian.hpp
- toolbox/sys/Runner.hpp
- toolbox/util.hpp
- toolbox/util/Concepts.hpp
- toolbox/util/IntTypes.hpp
- toolbox/util/String.hpp
- toolbox/util/TypeTraits.hpp
- toolbox/util/Utility.hpp
Adds some basic concepts and uses them to replace instances of enable_if
style sfinae.
SDB-3166
> feat: add initial concepts and replace sfinae

- bench/Util.bm.cpp
> chore: fixes breaking changes from gcc 12

- .github/workflows/ci-build.yml
- .github/workflows/gh-pages.yml
- .github/workflows/release.yml
- CMakeLists.txt
Upgrade to clang version 13.
SDB-3271
> build: update clang version in toolset

- example/HttpServ.cpp
- toolbox/sys/Log.hpp
- toolbox/sys/Log.ut.cpp
- toolbox/sys/Logger.cpp
- toolbox/sys/Logger.hpp
> feat(logger): rename warning level to warn

- toolbox/sys/Log.hpp
- toolbox/sys/Log.ut.cpp
- toolbox/sys/Logger.cpp
- toolbox/sys/Logger.hpp
new log level is required to collect metric data from applications
> feat: Add new log level to C++ logger

- toolbox/bm/Context.cpp
- toolbox/bm/Context.hpp
- toolbox/http/Stream.cpp
- toolbox/io/Reactor.cpp
- toolbox/io/Timer.cpp
- toolbox/util/Argv.cpp
- toolbox/util/Argv.hpp
- toolbox/util/String.hpp
Also correctly adds auto* when deducing a pointer.
> fix: improve automatic move & trivial destruction

- toolbox/util/Utility.cpp
- toolbox/util/Utility.hpp
- toolbox/util/Utility.ut.cpp
Add a new stod function for check if parse success or failed.
SDB-4065
> SDB-4065: add a new stod function

- toolbox/sys/Logger.cpp
- toolbox/sys/Logger.hpp
> feat(log): use lockfree queue for AsyncLogger

- toolbox/util/RefCount.hpp
SDB-4089
[SDB-4089]: https://reactivemarkets.atlassian.net/browse/SDB-4089?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(util): silence false positive in gcc-12

- .github/workflows/ci-build.yml
- .github/workflows/gh-pages.yml
- .github/workflows/release.yml
SDB-4089
[SDB-4089]: https://reactivemarkets.atlassian.net/browse/SDB-4089?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(workflows): update toolset to v0.20.0

- toolbox/contrib/robin_hood.h
Updates the most recent version of robin_hood.h
Also contains a modification to allow to build with clang-15:
```
209: && !defined(__clang__)
```
SDB-4255
> chore(contrib): update robin_hood.h

- example/EchoClnt.cpp
- example/EchoServ.cpp
- toolbox/io/Handle.ut.cpp
- toolbox/io/Timer.cpp
- toolbox/sys/Logger.cpp
- toolbox/util/Config.cpp
- toolbox/util/Options.cpp
- toolbox/util/VarSub.cpp
> chore: support clang-15

- toolbox/net/Frame.cpp
- toolbox/net/Frame.hpp
- toolbox/net/Frame.ut.cpp
- toolbox/resp/Parser.hpp
- toolbox/util/Utility.hpp
Use 2 byte binary encoded integers and provide and option to encode in little endian and big endian.
SDB-4987
> feat: use 2 byte binary encoded integers

- .github/workflows/ci-build.yml
- .github/workflows/gh-pages.yml
- .github/workflows/release.yml
> chore: update toolset to v0.24.0

- toolbox/net/Frame.hpp
- toolbox/net/Frame.ut.cpp
> feat(equity): itchctl - fix itch message length in incoming message

- toolbox/io/Runner.cpp
- toolbox/io/Runner.hpp
Added optional metricated reactor loop
SDB-5759
> feat: Added optional metricated reactor loop

- toolbox/io/Runner.cpp
- toolbox/io/Runner.hpp
Improved callback context
SDB-5759
> feat: improved callback context

- toolbox/io/Runner.cpp
- toolbox/io/Runner.hpp
Removed unnecessary MetricContext
SDB-5759
> feat: Removed unnecessary MetricContext

- bench/CMakeLists.txt
- bench/Histogram.bm.cpp
> test: add histogram microbenchmarks

- .github/workflows/ci-build.yml
- .github/workflows/gh-pages.yml
- .github/workflows/release.yml
> build: update toolset to v0.30.0

- toolbox/util/Config.ut.cpp
- toolbox/util/VarSub.cpp
- toolbox/util/VarSub.ut.cpp
Escapes not handled correctly by variable substitution.
SDB-6523
> fix: incorrect escape handling

- toolbox/io/Runner.cpp
Fixed microseocond loop timing.
SDB-6617
> bug: Fixed microseocond loop timing

- toolbox/io/Runner.cpp
- toolbox/io/Runner.hpp
Added reactor-loop completion callback.
SDB-6647
> feat: Added reactor-loop completion callback

- .github/workflows/ci-build.yml
- .github/workflows/gh-pages.yml
- .github/workflows/release.yml
> feat(cpp): Upgrade to GCC 13 and Clang 17

- toolbox/io/Buffer.cpp
- toolbox/io/Buffer.hpp
> feat(io): Inline prepare buffer function

- .github/workflows/ci-build.yml
- .github/workflows/gh-pages.yml
- .github/workflows/release.yml
> build: update toolset to v0.33.0

- toolbox/bm/Utility.hpp
- toolbox/hdr/Utility.ut.cpp
- toolbox/http/Url.ut.cpp
- toolbox/io/Epoll.hpp
- toolbox/io/Event.hpp
- toolbox/net/Endian.hpp
- toolbox/net/IoSock.ut.cpp
- toolbox/net/Protocol.hpp
- toolbox/net/Socket.ut.cpp
- toolbox/sys/PidFile.cpp
- toolbox/sys/Thread.cpp
- toolbox/util/Allocator.hpp
- toolbox/util/Array.ut.cpp
- toolbox/util/Config.hpp
- toolbox/util/Options.hpp
- toolbox/util/String.hpp
- toolbox/util/Struct.hpp
- toolbox/util/Tokeniser.hpp
- toolbox/util/Tokeniser.ut.cpp
- toolbox/util/Variant.hpp
> feat(chore): Headers cleanup

- .github/workflows/ci-build.yml
- .github/workflows/gh-pages.yml
- .github/workflows/release.yml
> build: Update toolset to v0.34.0

- toolbox/io/File.hpp
> feat(io): Add remove() file operation

- .github/workflows/ci-build.yml
- .github/workflows/gh-pages.yml
- .github/workflows/release.yml
> build: Upgrade to GCC 14 and Clang 18

- .github/workflows/ci-build.yml
- .github/workflows/gh-pages.yml
- .github/workflows/release.yml
Adds clang-tidy to the container
> chore(workflows): Update to build v0.36.0

- toolbox/io/Timer.cpp
- toolbox/io/Timer.hpp
Remove unused data member and allocation parameters. Minor correction to Slab size calculation.
> feat(timer): Minor refactoring and improvements

- toolbox/CMakeLists.txt
- toolbox/util/Config.cpp
- toolbox/util/Config.hpp
- toolbox/util/Config.ut.cpp
- toolbox/util/Options.hpp
- toolbox/util/String.cpp
- toolbox/util/String.hpp
- toolbox/util/TypeTraits.hpp
- toolbox/util/TypeTraits.ut.cpp
- toolbox/util/Utility.hpp
> feat: Extend config to allow multiple values per key

- toolbox/util/Config.cpp
- toolbox/util/Config.hpp
- toolbox/util/Config.ut.cpp
> Temporarily remove duplicate key validation

- toolbox/bm/Utility.hpp
- toolbox/hdr/Utility.ut.cpp
- toolbox/http/Url.ut.cpp
- toolbox/io/Epoll.hpp
- toolbox/io/Event.hpp
- toolbox/net/Endian.hpp
- toolbox/net/IoSock.ut.cpp
- toolbox/net/Protocol.hpp
- toolbox/net/Socket.ut.cpp
- toolbox/sys/PidFile.cpp
- toolbox/sys/Thread.cpp
- toolbox/util/Allocator.hpp
- toolbox/util/Array.ut.cpp
- toolbox/util/Config.hpp
- toolbox/util/Options.hpp
- toolbox/util/String.hpp
- toolbox/util/Struct.hpp
- toolbox/util/Tokeniser.hpp
- toolbox/util/Tokeniser.ut.cpp
- toolbox/util/Variant.hpp
> chore: Headers cleanup

- toolbox/io/Runner.cpp
> feat: Remove cycles taking zero mics from stats

- toolbox/util/Version.hpp
> chore: Remove implicit conversion to Version

- toolbox/io/Reactor.cpp
- toolbox/io/Reactor.hpp
- toolbox/io/Reactor.ut.cpp
> feat: Add file descriptor prioritisation in the Reactor

- toolbox/util/OStreamBase.hpp
[do_]prepare_space can throw.
SDB-8506
> fix(util): Fix noexcept-ness

- toolbox/CMakeLists.txt
- toolbox/util/OStreamBase.cpp
- toolbox/util/OStreamBase.hpp
Following the convention.
SDB-8506
> chore: Add cpp file corresponding to hpp file

- toolbox/util/Finally.hpp
The function (fn_) gets called multiple times if the class itself is moved from
SDB-8765
> fix(util): Fix move semantics of Finally/make_finally

- toolbox/util/Finally.hpp
> chore(util): Make Finally class immovable

- toolbox/io/Reactor.cpp
- toolbox/io/Reactor.hpp
- toolbox/io/Reactor.ut.cpp
> feat: Allow yielding to Reactor during I/O processing

- toolbox/net/IoSock.hpp
- toolbox/net/Socket.hpp
> feat: Plumbing for hardware receive timestamps

- toolbox/sys/Date.hpp
- toolbox/sys/Date.ut.cpp
> feat: Introduce function that converts IsoDate to UnixTime

- bench/Net.bm.cpp
- toolbox/http/Conn.hpp
- toolbox/sys/Logger.cpp
- toolbox/sys/Logger.hpp
- toolbox/util/Storage.hpp
- toolbox/util/Stream.hpp
> fix(logger): Allocate log messages from standard free-store

- toolbox/io/Reactor.cpp
- toolbox/io/Reactor.hpp
- toolbox/io/Reactor.ut.cpp
> chore: Remove immediate reactor mode
