reactivemarkets/toolbox-cpp

- CMakeLists.txt
Generate CNAME file on the gh-pages branch. This is required to enable use of a custom DNS domain for Doxygen documentation hosted on GitHub pages.
> Generate CNAME file for custom domain

- .circleci/config.yml
CircleCI does not run workflows for tags unless you explicitly specify tag filters. Additionally, if a job requires any other jobs (directly or indirectly), you must use regular expressions to specify tag filters for those jobs.
> Fix tag release build

- toolbox/net/Resolver.cpp
GCC 9.1 exposed a dormant bug in the DNS resolver that causes the run loop to crash when clearing tasks from the queue. The crash was caused by accessing uninitialised elements of a local array.
> DNS resolver crashes in GCC 9.1

- CONTRIBUTING.md
- toolbox/util/Exception.cpp
- toolbox/util/Exception.hpp
- toolbox/util/Exception.ut.cpp
Although the Exception class is designed to represent different kinds of exception, the current JSON format is quite specific to HTTP. The format should be generalised and brought more in line with the emerging OpenAPI standard.
Closes #27
> Generalise JSON exception format

- toolbox/CMakeLists.txt
- toolbox/util/Benchmark.cpp
- toolbox/util/Benchmark.hpp
- toolbox/util/Traits.hpp
- toolbox/util/Utility.bm.cpp
- toolbox/util/Utility.cpp
- toolbox/util/Utility.hpp
- toolbox/util/Utility.ut.cpp
Add basic benchmarking mechanism, with an emphasis on microbenchmarks.
Basic usage:
```bash
bin/toolbox-bench | column -t
bin/toolbox-bench --filter hex | column -t
bin/toolbox-bench --filter hex --random | column -t
```
> GH-30 Benchmarking functionality

- toolbox/util/Utility.bm.cpp
The "%lu" format expects an argument of type "long unsigned int", but "int64_t" is an alias for "long long int" on ARM32 platforms.
Closes #32
> Arm build broken by dec_digits4

- example/EchoClnt.cpp
- example/EchoServ.cpp
- example/HttpServ.cpp
- toolbox/http/App.hpp
- toolbox/http/Conn.hpp
- toolbox/http/Serv.hpp
- toolbox/net/Socket.hpp
- toolbox/net/StreamAcceptor.hpp
- toolbox/net/StreamConnector.hpp
Add new `on_sock_init` lifecycle callback, so that applications are given an opportunity to set socket options such as `SO_RCVBUF` and `SO_SNDBUF`.
This change also includes refactoring to make callback naming conventions clearer and more consistent.
Closes #35
> Improve socket option support

- .gitignore
- toolbox/CMakeLists.txt
- toolbox/hdr.hpp
- toolbox/hdr/HdrHistogram.cpp
- toolbox/hdr/HdrHistogram.hpp
- toolbox/hdr/HdrHistogram.ut.cpp
- toolbox/hdr/HdrHistogramIterator.cpp
- toolbox/hdr/HdrHistogramIterator.hpp
- toolbox/util/Benchmark.cpp
- toolbox/util/Benchmark.hpp
- toolbox/util/Utility.cpp
Integration with bencharking utils via -o hdr and -o stat options
While functional from missing things include:
* Correct iterator semantics
* Load / Dump capabilities
* Support for different sizes (currently using uint64_t)
Close #39
> Add initial version of HdrHistogram

- toolbox/io/Epoll.hpp
- toolbox/io/EpollReactor.cpp
- toolbox/io/EpollReactor.hpp
- toolbox/io/Muxer.hpp
- toolbox/sys/Log.hpp
In the initial `epoll_create()` implementation, the size argument informed the kernel of the number of file descriptors that the caller expected to add to the epoll instance. Modern kernels no longer require this hint.
Closes #44
> Remove epoll_create size hint

- toolbox/CMakeLists.txt
- toolbox/bm/Range.cpp
- toolbox/bm/Record.cpp
- toolbox/bm/Suite.cpp
- toolbox/hdr.hpp
- toolbox/hdr/Histogram.cpp
- toolbox/hdr/Histogram.hpp
- toolbox/hdr/Histogram.ut.cpp
- toolbox/hdr/Iterator.cpp
- toolbox/hdr/Iterator.hpp
- toolbox/hdr/Iterator.ut.cpp
- toolbox/hdr/Utility.cpp
- toolbox/hdr/Utility.hpp
- toolbox/hdr/Utility.ut.cpp
Refactor hdr package, so that it is more closely aligned to HdrHistogram_c. The advantage being that upstream bug fixes are easier to track and integrate into the C++ port.
Statistical functions that depend on iterators have been moved to a separate file in order to break a cyclic dependency between files.
Improve unit-test coverage has also been improved in this commit.
> Align HdrHistogram to C version

- etc/cppcheck-suppressions.txt
- example/EchoClnt.cpp
- example/EchoServ.cpp
- example/HttpServ.cpp
- toolbox/CMakeLists.txt
- toolbox/hdr/Histogram.ut.cpp
- toolbox/hdr/Utility.ut.cpp
- toolbox/io/Runner.cpp
- toolbox/net/Runner.cpp
- toolbox/net/Runner.ut.cpp
- toolbox/sys/Thread.cpp
- toolbox/sys/Thread.hpp
- toolbox/sys/Thread.ut.cpp
- toolbox/util.hpp
- toolbox/util/Path.cpp
- toolbox/util/Path.hpp
- toolbox/util/Path.ut.cpp
This PR provides the following enhancements as separate commits:
1) Specialise TypeTraits for filesystem path
The ThreadConfig structure should be extended to include an isolcpus-style affinity mask, along with helper functions for parsing and setting thread affinity.
2) Extend thread config to include affinity
Add TypeTraits specialisation for filesystem paths, so that paths can be specified as arguments to command-line options.
> Path and thread affinity enhancements

- bench/Util.bm.cpp
- toolbox/CMakeLists.txt
- toolbox/util.hpp
- toolbox/util/Bits.cpp
- toolbox/util/Bits.hpp
- toolbox/util/Math.hpp
- toolbox/util/Tuple.ut.cpp
- toolbox/util/Utility.cpp
- toolbox/util/Utility.hpp
The hex_digits function was using the long version of the bultin clz function (`__builtin_clzl`). Long integers are 32-bits on ARM32. A function template has been added to ensure that the correct intrinsic is used in future based on the size of the integer type.
Closes #51
> bug: the hex_digits function is broken on ARM32 builds

- toolbox/util/Config.hpp
Add rvalue-reference overloads for methods that read configuration from streams.
> feat: rvalue-reference stream overloads

- CMakeLists.txt
- doc/CMakeLists.txt
- doc/Doxyfile.in
- toolbox/hdr/Histogram.hpp
Move Doxygen target to the doc directory, so that it is more consistent with the downstream Matchbox project and paves the way for additional kinds of documentation.
> chore(doxygen): move Doxygen target to doc directory

- bench/CMakeLists.txt
- bench/Map.bm.cpp
- etc/cppcheck-suppressions.txt
- example/HttpServ.cpp
- toolbox/CMakeLists.txt
- toolbox/contrib/http_parser.c
- toolbox/contrib/http_parser.h
- toolbox/contrib/robin_hood.h
- toolbox/contrib/ryu/d2s.c
- toolbox/util.hpp
- toolbox/util/RobinHood.cpp
- toolbox/util/RobinHood.hpp
The `robin_hood::unordered_map` container is a fast, efficient hashtable implementation based on Robin Hood hashing. It can be used as a drop-in replacement for `std::unordered_map`.
> feat(util): switch to robin_hood::unordered_map

- CMakeLists.txt
- example/EchoClnt.cpp
- toolbox/net/Socket.hpp
The TCP_SYNCNT option specifies the number of SYN retransmits that a TCP socket should send before aborting the connection attempt.
> feat(socket): add support for TCP_SYNCNT option

- CMakeLists.txt
- example/EchoClnt.cpp
- example/EchoServ.cpp
- toolbox/http/Conn.hpp
Handling read events before write events reduces the possibility of a broken pipe exception.
> Handle read events before write

- example/EchoClnt.cpp
- example/EchoServ.cpp
- toolbox/http/Conn.hpp
Rework the I/O event handling on HTTP connections to reduce the number of context switches.
> Reduce context switches

- toolbox/ipc/MpmcQueue.hpp
- toolbox/ipc/Msg.hpp
Adopt new convention of using new instead of create as the factory function prefix.
> Rename create functions

- toolbox/net/RateLimit.hpp
Fix incorrect exception specifications used for rate limiter in the previous commit.
> Correct exception specifications

- CMakeLists.txt
Use Reactive option names for CMake configuration, so that they cooperate more intuitively with root projects in the Reactive organisation.
> refactor: use Reactive option names

- .github/workflows/ci-build.yml
- .github/workflows/gh-pages.yml
- .github/workflows/release.yml
- CMakeLists.txt
- README.md
- etc/cppcheck-suppressions.txt
- etc/dotdepend.pl
- toolbox/io/Reactor.hpp
Upgrade toolchain image to Clang and GCC 9.x, so that we can use features from C++20.
DEV-2024
> DEV-2024: update C++ toolchain

- example/EchoClnt.cpp
Follow the PostgreSQL error style guide on past and present tense:
https://www.postgresql.org/docs/9.1/error-style-guide.html
DEV-2138
> chore: improve error messages

- example/HttpServ.cpp
- toolbox/hdr/Iterator.hpp
- toolbox/http/Error.cpp
- toolbox/http/Stream.hpp
- toolbox/net/Error.cpp
- toolbox/util/Ryu.ut.cpp
- toolbox/util/Stream.hpp
Code does not compile on Clang v10 due to a number of pedantic warnings. (We treat warnings as errors.)
DEV-2162
> fix: code does not compile on Clang v10

- cppcheck.sh.in
- etc/cppcheck-suppressions.txt
Update usage of cppcheck. Switch to C++20 and remove fixed suppressions.
Closes #89
> Update usage of cppcheck

- CMakeLists.txt
Enable runtime type information to enable library code to be wrapped using pybind11 Python bindings.
DEV-2223
> feat: enable runtime type information

- toolbox/net/Resolver.cpp
- toolbox/net/Resolver.hpp
- toolbox/net/Runner.cpp
Add a reset method to the resolver, so that a single instance can be reset and reused multiple times. This is required for downstream Python bindings.
DEV-2226
> feat: reset resolver before running

- example/HttpServ.cpp
- toolbox/http/App.cpp
- toolbox/http/App.hpp
- toolbox/http/Conn.hpp
- toolbox/http/Serv.hpp
Drop the "Base" suffix from HttpAppBase, because this is the only class type in this project that follows this convention.
> refactor: rename HttpAppBase to HttpApp

- toolbox/io/Timer.hpp
Modify timer cancellation function, so that it can be safely called on a null timer.
DEV-2655
> feat: check for null on timer cancellation

- example/HttpServ.cpp
- toolbox/http/App.hpp
- toolbox/http/Conn.hpp
- toolbox/http/Stream.cpp
- toolbox/http/Stream.hpp
- toolbox/sys/Log.hpp
- toolbox/util/Exception.hpp
- toolbox/util/Stream.hpp
- toolbox/util/Stream.ut.cpp
Add an "O" prefix to output stream type names, so that they follow industry convention.
DEV-2657
> refactor: rename output stream types

- toolbox/sys/Log.hpp
- toolbox/sys/Log.ut.cpp
Although a "raw" (char*, size_t) function already exists by simplifying the
Log class a bit we can also allow custom inserter overloads directly,
which can be used for unformatted logging if required.
> feat: Improve unformated logging

- bench/CMakeLists.txt
- toolbox/http/Stream.cpp
- toolbox/http/Stream.hpp
- toolbox/util/Stream.cpp
- toolbox/util/Stream.hpp
Replace the "reset" free function with an equivalent I/O manipulator that can be used to reset the state of the logger.
> feat(stream): manipulator for i/o state reset

- toolbox/sys/Limits.hpp
- toolbox/sys/Log.hpp
Increase the maximum log line size so that it can accommodate most market-data messages.
DEV-2732
> feat(log): increase log line size

- .github/workflows/gh-pages.yml
- .github/workflows/release.yml
A moderate security vulnerability has been identified in the GitHub Actions runner that can allow environment variable and path injection in workflows that log untrusted data to STDOUT. This can result in environment variables being introduced or modified without the intention of the workflow author.
DEV-2747
> fix(github): remove set-env and add-path commands

- .github/workflows/gh-pages.yml
- .github/workflows/release.yml
The "v" prefix was trimmed from the release tag using a sed expression.
Bash parameter expansions have direct support for prefix removal, so the sed subshell is unnecessary.
DEV-2747
> refactor(github): no need for sed subshell

- toolbox/sys/Log.cpp
- toolbox/sys/Log.hpp
- toolbox/sys/Log.ut.cpp
- toolbox/util/Allocator.cpp
- toolbox/util/Allocator.hpp
- toolbox/util/Storage.hpp
- toolbox/util/Stream.hpp
Replace the Storage class template with a simple void pointer manager by a unique_ptr, where the unique_ptr's deleter encapsulates the allocation size.
Using a class template for the deleter instead of a function pointer also ensures that the unique_ptr has no overhead in terms of its size. I.e. it does not need to store a function pointer.
Remove unused aligned allocator function overloads.
DEV-1325
> feat(log): replace Storage class with void pointer

- CONTRIBUTING.md
- example/EchoClnt.cpp
- example/EchoServ.cpp
- example/HttpServ.cpp
- toolbox/io/Hook.cpp
- toolbox/io/Reactor.cpp
- toolbox/io/Runner.cpp
- toolbox/io/Timer.cpp
- toolbox/net/Runner.cpp
- toolbox/util/Exception.cpp
- toolbox/util/Exception.ut.cpp
Standard exception classes such as std::system_error format exception messages such that the "what" argument precedes the error code. Toolbox exceptions should adopt this convention for consistency.
DEV-2766
> feat: conventional error message format

- toolbox/CMakeLists.txt
Library names should use underscores instead of hyphens.
There are three reasons for this change:
1. Downstream projects use Toolbox in native Python modules. Python modules can not use hyphens, only underscores. The shared libraries that implement native modules should also use underscores so that the shared library name matches the Python module name.
2. Downstream projects use Toolbox libraries alongside Rust libraries. Rust libraries built by the Cargo build tool always use underscores in their names.
3. Boost shared library names use underscores.
DEV-3269
> feat(build): use underscores for library names

- .github/workflows/ci-build.yml
The CI build runs clang-format to check that all files are correctly formatted.
Fix a typo in this check and use the Git "-uno" option so that untracked files are ignored when checking for modifications.
DEV-3273
> build: improve clang-format check

- CMakeLists.txt
- etc/cppcheck-suppressions.txt
Add support for project-specific cppcheck scripts, so that downstream projects can define their own program options.
DEV-3299
> chore: add support for project-specific cppcheck

- toolbox/CMakeLists.txt
- toolbox/bm.hpp
- toolbox/bm/Benchmark.cpp
- toolbox/bm/Benchmark.hpp
- toolbox/bm/Context.cpp
- toolbox/bm/Context.hpp
- toolbox/bm/Suite.hpp
Rename context types from Ctx to Context for consistency for other projects.
DEV-3307
> refactor: rename context types for consistency

- toolbox/contrib/README.txt
- toolbox/contrib/robin_hood.h
The latest Robin hood header includes a small fix that is required when compiling with GCC 11.
DEV-3343
> chore: upgrade Robin hood dependency

- toolbox/net/Socket.hpp
Changes the exception message thrown when getaddrinfo fails to resolve
the address to show the address that it was trying to resolve. This in
turn will cause it to show the address in the log.
DEV-3262
> chore: Include the address in DNS resolution error

- toolbox/util/Utility.cpp
- toolbox/util/Utility.hpp
- toolbox/util/Version.hpp
- toolbox/util/Version.ut.cpp
Add a size method to the Version class that returns the length of the equivalent string representation.
DEV-3356
> feat: add size method to Version

- toolbox/net/Resolver.cpp
- toolbox/net/Resolver.hpp
- toolbox/net/Runner.cpp
Fix resolver stop data race, and remove reset call in
run_resolver function.
DEV-3384
> DEV-3384: data race on resolver stop

- toolbox/net/Resolver.cpp
- toolbox/sys/Log.hpp
- toolbox/sys/Log.ut.cpp
- toolbox/sys/Logger.cpp
- toolbox/sys/Logger.hpp
Add a timstamp parameter to the Logger's write_log method. This parameter allows the log time to be captured on the originating thread and passed to a backend logger running on a different thread.
DEV-1325
> feat: add timestamp parameter to logger

- toolbox/sys/Log.ut.cpp
- toolbox/sys/Logger.cpp
- toolbox/sys/Logger.hpp
Add a new 0/None enum value to LogLevel so that it has an exceptional
default value. This also increments the value of all previous values.
BREAKING CHANGE: All previous logger levels have had their values
increased by 1
> refactor(log)!: Add a 0/None value to log level

- toolbox/util/String.hpp
Use memset to apply buffer padding in all pstrcpy function implementations.
> fix: use memset to padding in pstrcpy functions

- CMakeLists.txt
The C++ build should require boost 1.74 or above because this is version used for official images built by the CI/CD system.
DEV-3425
> chore(build): require boost 1.74 or above

- CMakeLists.txt
Statically compiled unit-test applications were failing with the following error:
Main.ut.cpp:(.text.startup+0xd): undefined reference to `boost::unit_test::unit_test_main(bool (*)(), int, char**)' collect2:
error: ld returned 1 exit status
This happens due conflicting use of Boost_USE_STATIC_LIBS and BOOST_TEST_DYN_LINK when shared builds are disabled but boost shared libraries are available. In this case the build sets the BOOST_TEST_DYN_LINK option even though Boost_USE_STATIC_LIBS is also set.
The solution is not to force the use of Boost static libraries, because it leads to more complex and unpredictable build scenarios
with minimal benefit.
DEV-3433
> fix(build): undefined reference to unit_test_main

- etc/dotdepend.pl
Building dependency graph images may result in the following error:
Use of uninitialized value $dlib in string eq at etc/dotdepend.pl line 104.
Use of uninitialized value $_ in concatenation (.) or string at etc/dotdepend.pl line 145.
Error: <stdin>: syntax error in line 29 near ';'
This is because the "libutil.h" dependency may not be prefixed with the path that is used to infer the library to which the dependency belongs.
DEV-3438
> fix(build): use of uninitialised value $dlib

- toolbox/sys/Trace.hpp
The Trace.hpp header references the TOOLBOX_HAVE_SYSTEMTAP pre-processor definition so the Config.h must be included.
DEV-3477
> fix(probe): probes depend on config header

- doc/CMakeLists.txt
We're now hosting directly on github without a cname.
> docs: removing CNAME generation

- toolbox/http/Exception.hpp
Allowing the http Exception class to inherit constructors from the base class is error prone because it would allow error_codes to be used with different error categories.
SDB-2875
> fix(http): remove constructor inheritance

- CMakeLists.txt
- toolbox/util/Config.hpp
- toolbox/util/Config.ut.cpp
The Config set method is not updating existing entries.
The insert_or_assign method should be used on the underlying map instead of emplace.
SDB-2935
> fix(config): config entries cannot be modified

- toolbox/util/Stream.hpp
- toolbox/util/Stream.ut.cpp
Blank log messages were being sent due to bad flag being set when buffer
was overrun, this was not causing any issues else where so we simply
reset the flag when resetting the buffer.
SDB-2962
> fix(util): reset ostream flags

- toolbox/util/Config.hpp
Remove redundant conversion for the specialised string_view getter in the Config class.
> feat(util): remove redundant conversion

- .gitignore
- toolbox/sys/Logger.cpp
Changes the formatting for date and time for stdlog to be consistent
with Go logging, this also increases the accuracy of the time to
microseconds.
SDB-3132
> chore(sys): change date time formatting for stdlog

- toolbox/util/Config.hpp
get returns a string_view to an iterator which is invalidated if set is called. Changing to a map as it doesn't invalidate iterators
SDB-3803
> fix: iterator invalidation reading config

- toolbox/net/Socket.hpp
- toolbox/net/StreamAcceptor.hpp
- toolbox/net/StreamConnector.hpp
Perform a runtime check to ensure that the Nagle is disabled, and throw an exception if it is not.
SDB-3832
> feat(net): ensure that Nagle is always disabled

- bench/Log.bm.cpp
- toolbox/bm/Benchmark.hpp
- toolbox/sys/Date.hpp
- toolbox/sys/Log.hpp
- toolbox/sys/Log.ut.cpp
- toolbox/sys/Logger.cpp
- toolbox/sys/Logger.hpp
- toolbox/sys/Thread.hpp
- toolbox/util/IntTypes.hpp
- toolbox/util/IntTypes.ut.cpp
- toolbox/util/Options.hpp
- toolbox/util/Stream.hpp
- toolbox/util/Struct.ut.cpp
The thread-id must be acquired on the caller's thread rather than on the logger's worker thread.
SDB-3845
> fix(log): acquire thread-id on caller thread

- toolbox/util/String.hpp
- toolbox/util/String.ut.cpp
Add set of lpstrcpy functions equivalent to pstrcpy family of functions, except that the destination buffers are left-padded instead of right-padded.
SDB-4805
> feat(util): add left-padded string functions

- toolbox/io/Reactor.cpp
- toolbox/io/Reactor.hpp
- toolbox/io/Runner.cpp
- toolbox/io/Runner.hpp
Extend Reactor metrics to include second histogram that records reactor event processing time.
SDB-5959
> feat: extend Reactor metrics to include elapsed time

- toolbox/net/Endpoint.cpp
- toolbox/net/Endpoint.hpp
- toolbox/net/Resolver.cpp
- toolbox/net/Resolver.hpp
Makes it easier to pass string_views to the function.
> chore(net): switch uri parameter to string_view

- toolbox/io/Reactor.cpp
- toolbox/io/Reactor.hpp
Add support for hooks that are called after all i/o and timer events have been dispatched. These hooks are called, and only if, work done in the cycle is greater than zero. And they are always called before EndOfCycleNoWait hooks.
SDB-6783
> feat(reactor): Add hooks for end of event dispatching

- toolbox/io/Buffer.hpp
Buffer::prepare() is called every time when sth is about to be written to the buffer, it includes calling of vector::resize().
It turned out that resize() is not so cheap if current capacity is more than requested size, because it touches newly requested chunk of memory.
Measurements showed that boost::vector does it a bit more efficient by using memset() while std::vector uses std::__uninitialized_default_n_a()
SDB-6760
> perf(fix): Use boost vector as underlying storage for the buffer instead of the std::vector

- toolbox/io/Buffer.hpp
io::Buffer has wptr and rptr which effectively controls buffer boundaries
SDB-6760
> perf(fix): Do not call boost::vector::clear()

- toolbox/io/Buffer.hpp
Made sure prepare only returns what is requested. This counters the issue where comsume() can reclaim ~50% buffer space in advance making available a lot more than expected.
SDB-6933
> feat: Made sure prepare only returns what is requested.

- toolbox/sys/Logger.hpp
Increase AsyncLogger queue size to reduce the likelihood of drops.
SDB-6988
> feat: Increase AsyncLogger queue size

- example/CMakeLists.txt
- example/HttpServ.cpp
- example/Inotify.cpp
- toolbox/CMakeLists.txt
- toolbox/io.hpp
- toolbox/io/Buffer.hpp
- toolbox/io/Handle.hpp
- toolbox/io/Inotify.cpp
- toolbox/io/Inotify.hpp
- toolbox/io/Runner.cpp
- toolbox/io/Runner.hpp
- toolbox/net/Resolver.cpp
- toolbox/net/Resolver.hpp
The inotify API provides a mechanism for monitoring filesystem events. Inotify can be used to monitor individual files, or to monitor directories. When a directory is monitored, inotify will return events for the directory itself, and for files inside the directory.
SDB-6742
> feat(io): Add support for inotify API

- example/Inotify.cpp
- toolbox/io/Inotify.cpp
- toolbox/io/Inotify.hpp
- toolbox/util/Tokeniser.hpp
On Kubernetes, inotify only receives the IN_DELETE_SELF event on config maps. This deletion event breaks the inotify watch and so code needs to handle re-establishing the watch every time the file is updated.
SDB-7208
> feat(io): Add support for dynamic k8s config loading

- toolbox/sys/Log.hpp
> fix(sys): Log macro has missing namespace qualifier

- toolbox/io/Handle.ut.cpp
- toolbox/net/Socket.hpp
- toolbox/sys/Log.ut.cpp
Fixes a possible nullptr string construction which will throw, hiding
the original error message.
Silences some other warnings on purposeful issues.
> fix: fix some issues caught by clang-analyzer

- .github/workflows/ci-build.yml
- CMakeLists.txt
Takes too long in CI builds, this will allow us to disable it for only those builds.
> chore(cmake): Allow disabling clang-tidy

- bench/Util.bm.cpp
- toolbox/util/Math.hpp
- toolbox/util/Utility.hpp
- toolbox/util/Utility.ut.cpp
**Note to reviewers: This pull request consists of 2 commits, so view separately for easier reviewing.**
In this commit, you may notice K=7 for the benchmarks. This means that 1 to 7 digit random numbers will be used for benchmarking i.e. [1, 10^7). The reasoning for that is because I think very large numbers (>7 digits) are much less common in production.
```
NAME                                                   COUNT       MIN       %50       %95       %99     %99.9    %99.99
------------------------------------------------------------------------------------------------------------------------
dec_digits_lib                                    3516840000         0         0         0         0         0         0
dec_digits_div                                    1205850000     0.002 …
```
> Improve dec_digits performance and benchmarking methodology

- bench/Util.bm.cpp
The uniform_int_distribution construction parameters form a closed range (i.e. inclusive range). selector_dist should only generate integers to digit_dists.size()-1 so fix that.
> fix(bm): fix random dist range parameter error

- toolbox/io/Reactor.cpp
- toolbox/io/Timer.cpp
- toolbox/io/Timer.hpp
Sometimes it is required that TimerQueue::dispatch finishes fast in a bounded amount of time while still making progress on the queued timers. In which case, you want dispatch to process a small number of queued
timers and then return back to caller.
Furthermore, limit the work done by low priority timer queue to just 1 in the reactor. This prevents too much time being taken by low priority timers if there are a lot of them eligible to be dispatched. They are low priority timers, so its ok if they are delayed by a little bit of time.
SDB-8174
> feat(timer): Allow limiting the work done by dispatch

- bench/Map.bm.cpp
- bench/Util.bm.cpp
- toolbox/CMakeLists.txt
- toolbox/util/Random.cpp
- toolbox/util/Random.hpp
- toolbox/util/Random.ut.cpp
Random number generation is ocurring more often in code. Random number generation is mainly done by
constructing and making use of std::random_device and std::mt19937. However, construction of these 2 objects is very expensive and should not be done regularly.
This commit adds an easy to use function for random number generation.
It also has good performance because it avoids constructing std::random_device and std::mt19937 each time.
SDB-7525
> feat: Add random int generating function

- .clang-tidy
`AnalyzeTemporaryDtors` has been deprecated for a while and has now been removed so having this option now breaks clang-tidy.
> fix(clang-tidy): Remove old option

- toolbox/io/Reactor.cpp
- toolbox/io/Reactor.ut.cpp
- toolbox/util/Random.ut.cpp
If low priority timers have bee been delayed for 100ms or more, then actively execute them (one each cycle) until all of the delayed ones have been cleared.
This provides progress of guarantee for low priority timers and ensures they are not left pending for a long time if there are no idle cycles.
SDB-8393
> feat: Actively execute low priority timers after threshold

- bench/CMakeLists.txt
- bench/Net.bm.cpp
- toolbox/net/Endpoint.cpp
- toolbox/net/Endpoint.ut.cpp
- toolbox/util/Stream.hpp
> perf: Improve performance of ipv4 address formatting

- toolbox/util/Exception.cpp
- toolbox/util/Exception.hpp
- toolbox/util/Stream.hpp
- toolbox/util/Stream.ut.cpp
This an issue because if we attempt to create an custom overloaded operator<< for OStaticStream then it results in ambiguous call compiler error as there are now 2 valid overloads (first is catch-all in toolbox, and 2nd our custom defined one).
The catch-all overload mainly exists to ensure that after several streaming operations, OStaticStream& (ref) is returned. This then allows the OStaticStream& to be implicity converted to a string. For example, consider an expression like so: err_msg() << a << b << c;
If the catch-all overload did not exist, then this expression would return a 'std::ostream&' rather than 'OStaticStream&'. This would prevent the stream from being turned into a string implicitly as std::ostream& is not implicitly convertible to a string_view.
It is only 'err_msg()' …
> chore: Remove catch-all overload of OStaticStream

- bench/CMakeLists.txt
- bench/Stream.bm.cpp
- toolbox/hdr/Utility.hpp
- toolbox/sys/Log.ut.cpp
- toolbox/sys/Time.hpp
- toolbox/sys/Time.ut.cpp
- toolbox/util/Options.hpp
- toolbox/util/Stream.hpp
- toolbox/util/Utility.hpp
Currently, our streaming overloads (operator<<) make use of io manipulators. This means any ostreams making use of such overloads are also required to implement IO manipulators -- this adds non-trivial complexity and state. Not only that, they are cumbersome to use, and typically require saving existing state and restoring it with an RAII object -- this is often forgotten, as is the case in our codebase.
The replacment is built on top of C++20's std::format.
SDB-8506
> chore: Replace use of ostream IO manipulators

- toolbox/http/Parser.hpp
- toolbox/http/Stream.cpp
- toolbox/io/Buffer.cpp
- toolbox/io/Buffer.ut.cpp
- toolbox/io/File.hpp
- toolbox/io/Stream.cpp
- toolbox/net/Frame.hpp
- toolbox/net/Frame.ut.cpp
- toolbox/net/Socket.hpp
buffer_cast was removed in boost 1.87
> chore: replace the now removed buffer_cast

- .github/workflows/gh-pages.yml
- toolbox/io/Buffer.hpp
buffer_cast removed in boost 1.87. All uses of it have been removed in a previous commit but this was missed.
Also fixes the GH Pages action.
> chore: Remove final instance of buffer_cast

- bench/Net.bm.cpp
- toolbox/io/Buffer.hpp
- toolbox/sys/Log.hpp
- toolbox/sys/Time.hpp
- toolbox/util/OStreamBase.hpp
- toolbox/util/Stream.hpp
- toolbox/util/Stream.ut.cpp
- toolbox/util/TypeTraits.hpp
SDB-8506
EDIT: Have run Log.bm.cpp and Net.bm.cpp benchmarks
Improvements ranging from 10% to 252% 
BEFORE:
```
------------------------------------------------------------------------------------------------------------------------
sync_null_logger                                   426146200     0.055     0.069     0.072     0.093     0.121     0.154
unformatted_null_logger                            552838000     0.048     0.054     0.056     0.063     0.086     0.104
async_logger                                         1417900     0.055     0.086      0.14     0.166     0.193     2.101
formatted_null_logger                              453439000      0.05     0.065     0.068     0.072      0.11     0.139
sync_file_logger                                   131022550     0.214     0.227 …
```
> feat: Custom OStream replacement

- example/HttpServ.cpp
- toolbox/io/Hook.hpp
- toolbox/io/Inotify.hpp
- toolbox/io/Reactor.hpp
- toolbox/io/Timer.hpp
- toolbox/util/Slot.hpp
- toolbox/util/Slot.ut.cpp
- toolbox/util/Traits.hpp
- toolbox/util/Traits.ut.cpp
BasicSlot template now takes callable signature as template parameter, just like std::function
SDB-8765
> feat!: Extend slots to allow return values

- toolbox/sys/Logger.cpp
Avoids a possible buffer overrun should the upper limit be incorrect. Will now instead just cut off the log message.
> chore(sys): Use snprintf over sprintf

- toolbox/CMakeLists.txt
GCC 15's libstdc++ now emits calls to __atomic_compare_exchange for certain 16-byte CAS operations (e.g. Boost.Lockfree's tagged_index). Clang does not add libatomic automatically, so the link step fails with "undefined reference to __atomic_compare_exchange".
Add 'atomic' to target_link_libraries so Clang builds succeed on all x86-64 configurations.
SDB-9349
> fix(build): link libatomic when using Clang ≥ 17

- toolbox/io/Reactor.cpp
If units are not the same, there is an implicit conversion that occurs within comparator. `Micros::max()` cannot be safely converted to nanos as it results in overflow, thus undefined behaviour.
SDB-9564
> fix: Ensure time comparison in same units

- toolbox/util/Config.hpp
- toolbox/util/Config.ut.cpp
> feat: Add for_each_section to MultiConfig
